/**
 * Action-audit value types (task T2.7; spec plan/08 §8.3 destructive-action
 * gating + audit, §8.8 observability "action audit log").
 *
 * The audit log records every *vehicle action* the app (or an extension) issues —
 * commands, parameter writes and mission writes — so an operator can review, in
 * order, what was sent, by whom, and how it resolved. These types are the
 * value-object surface; {@link import('./audit-log').AuditLog} is the service.
 *
 * They are intentionally MAVLink-agnostic: an entry is a plain, serialisable
 * record (no live handles), so the log can be exported to disk for incident
 * review (spec plan/08 §8.8) without dragging in protocol types.
 */

/** Category of audited vehicle action. */
export type AuditKind = 'command' | 'param-set' | 'mission-write';

/**
 * Lifecycle status of an audited action. An action is appended as `pending`
 * (start), then updated to `ok` / `error` when its async result arrives, or is
 * recorded as `cancelled` when the operator declines the safety confirmation.
 */
export type AuditStatus = 'pending' | 'ok' | 'error' | 'cancelled';

/**
 * Origin of an action: `'ui'` for operator-initiated UI actions, or an extension
 * id (any other string) when a sandboxed extension/script issued it (spec
 * plan/08 §8.3 "audit-logged with origin (UI vs which extension/script)").
 */
export type AuditOrigin = 'ui' | (string & {});

/** A single serialisable parameter value carried by an audit entry. */
export type AuditValue = number | string | boolean;

/** Structured parameters recorded with an action (named map or ordered list). */
export type AuditParams = Readonly<Record<string, AuditValue>> | readonly AuditValue[];

/**
 * One immutable audit record. Identity is the generated {@link id}; the log
 * mutates an entry only by replacing it with an `update`d copy (callers always
 * see a frozen snapshot via {@link import('./audit-log').AuditLog.list}).
 */
export interface AuditEntry {
  /** Stable, log-unique id (used as render key + `update` target). */
  readonly id: string;
  /** Wall-clock start time in milliseconds. */
  readonly tMs: number;
  /** Action category. */
  readonly kind: AuditKind;
  /** Short human-readable summary (already localised by the caller). */
  readonly summary: string;
  /** Who issued the action (`'ui'` or an extension id). */
  readonly origin: AuditOrigin;
  /** Lifecycle status. */
  readonly status: AuditStatus;
  /** Optional structured parameters (e.g. command params, param name/value). */
  readonly params?: AuditParams;
  /** Optional result/outcome detail (e.g. `'ok'`, an error message, MAV_RESULT). */
  readonly result?: string;
  /** Wall-clock completion time in milliseconds (set on `ok`/`error`/`cancelled`). */
  readonly tEndMs?: number;
}

/**
 * Fields accepted by {@link import('./audit-log').AuditLog.append}. `id` is
 * always generated by the log; `status` defaults to `pending`, `origin` to
 * `'ui'`, and `tMs` to the log's clock.
 */
export interface AuditEntryInput {
  /** Action category. */
  kind: AuditKind;
  /** Short human-readable summary. */
  summary: string;
  /** Who issued the action; defaults to `'ui'`. */
  origin?: AuditOrigin;
  /** Initial lifecycle status; defaults to `'pending'`. */
  status?: AuditStatus;
  /** Optional structured parameters. */
  params?: AuditParams;
  /** Optional result detail (usually set later via `update`). */
  result?: string;
  /** Override the log clock for this entry (deterministic tests). */
  tMs?: number;
  /** Optional explicit completion time. */
  tEndMs?: number;
}

/** Mutable fields accepted by {@link import('./audit-log').AuditLog.update}. */
export interface AuditPatch {
  /** New lifecycle status. */
  status?: AuditStatus;
  /** Result/outcome detail. */
  result?: string;
  /** Replace the summary (rare; e.g. enrich after the fact). */
  summary?: string;
  /** Completion time in milliseconds. */
  tEndMs?: number;
}

/** Subscriber callback: receives the current (frozen) entry list newest-last. */
export type AuditListener = (entries: readonly AuditEntry[]) => void;

/** Construction options for {@link import('./audit-log').RingAuditLog}. */
export interface AuditLogOptions {
  /** Time source for `tMs`/`tEndMs`; defaults to `Date.now`. */
  clock?: () => number;
  /** Maximum retained entries (oldest evicted); defaults to {@link DEFAULT_MAX_ENTRIES}. */
  maxEntries?: number;
  /** Id generator; defaults to a per-log monotonic counter. */
  idFactory?: () => string;
}

/** Default bound on retained audit entries. */
export const DEFAULT_MAX_ENTRIES = 1000;
